# deployment for Mysql
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: expense
  # Labels of deployment resource
  labels:
    app: mysql
    tier: mysql
    project: expense
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
      tier: mysql
      project: expense
  template:
    metadata:
      labels:
        app: mysql
        tier: mysql
        project: expense
    spec:
      containers:
        - name: nginx
          image: rahul8096/mysql:1.0.0
---
# give the Cluster Ip for Connecting the Backend service to Mysql database
apiVersion : v1
kind: Service
metadata : 
name : mysql
spec : 
 selector:
 app : mysql
 tier : mysql
 project : expense
ports : 
- protpcol: TCP
  port : 3306 # Service Port
  targerport : 3306 # Mandotory Port 





